forge "https://forge.puppet.com"

mod 'puppetlabs-stdlib', '4.25.1'
mod 'puppetlabs-apt', '5.0.0'
mod 'puppetlabs-concat', '4.2.1'
mod 'puppet-nginx', '0.13.0'
mod 'puppetlabs-gcc', '0.3.0'
mod 'willdurand-nodejs', '2.0.2'
mod 'stahnma-epel', '1.3.1'
mod 'puppet-python', '2.1.0'
mod 'ajcrowe-supervisord', '0.6.1'
mod 'puppet-archive', '3.1.0'
mod 'puppet-grafana', '4.5.0'
mod 'puppetlabs-firewall', '1.12.0'
mod 'saz-memcached', '3.3.0'